spring:
  application:
    name: spring-boot-appmap-integration

  datasource:
    url: jdbc:mysql://localhost:3306/ctz_test
    username: root
    password: G@ur@v@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show-sql: true
appmap:
  recording:
    auto: true